<a href="https://colab.research.google.com/github/ytg000629/Building_Safety_Indicator/blob/main/Modeling/pyspark_%E1%84%85%E1%85%A2%E1%86%AB%E1%84%83%E1%85%A5%E1%86%B7%E1%84%91%E1%85%A9%E1%84%85%E1%85%A6%E1%84%89%E1%85%B3%E1%84%90%E1%85%B3%2C_%E1%84%80%E1%85%A7%E1%86%AF%E1%84%8C%E1%85%A5%E1%86%BC%E1%84%90%E1%85%B3%E1%84%85%E1%85%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.4.0.tar.gz (310.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.4.0-py2.py3-none-any.whl size=311317145 sha256=b7888c171905565541fe2f35220e4fd2dacdb8787139f593a2f054ac60e023c1
  Stored in directory: /root/.cache/pip/wheels/7b/1b/4b/3363a1d04368e7ff0d408e57ff57966fcdf00583774e761327
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.4.0

In [ ]:
import pyspark as spark
from pyspark.sql import SparkSession
import numpy as np
import pandas as pd
import glob
from pyspark import SparkContext
from pyspark.sql import Row
from pyspark.sql import SQLContext
sc = SparkContext()
sqlContext = SQLContext(sc)

ValueError: ignored

In [ ]:
df = pd.read_csv('./drive/MyDrive/final_data.csv',encoding='utf-8')
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,등급
0,3,0.2,2.2,491,54.273750,18096.210463,11774.100170,1,0,0,3등급
1,2,9.3,1.9,703,49.554054,18096.210463,11774.100170,0,0,1,3등급
2,1,-4.2,1.8,2000,31.607682,18096.210463,11774.100170,0,1,0,3등급
3,1,-4.4,4.5,558,50.355768,18096.210463,11774.100170,0,0,1,3등급
4,3,1.5,5.9,634,43.742292,18096.210463,11774.100170,1,0,0,3등급
...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,53.538975,1508.576577,2753.428205,0,1,0,3등급
21248,2,-0.3,2.0,2000,48.487317,1508.576577,2753.428205,0,0,1,3등급
21249,1,4.7,0.6,137,55.215504,10826.115819,30619.671937,0,0,0,2등급
21250,2,2.3,1.1,950,53.850522,10826.115819,30619.671937,0,0,1,3등급
21251,1,33.9,1.7,2000,61.490694,1595.099346,2541.476440,0,0,1,3등급

In [ ]:
def convert_Int(x) :
  try :
    result = int(x[0])
  except ValueError :
    pass

  return result

In [ ]:
df["등급"] = df.등급.apply(lambda x : convert_Int(x))
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,등급
0,3,0.2,2.2,491,54.273750,18096.210463,11774.100170,1,0,0,3
1,2,9.3,1.9,703,49.554054,18096.210463,11774.100170,0,0,1,3
2,1,-4.2,1.8,2000,31.607682,18096.210463,11774.100170,0,1,0,3
3,1,-4.4,4.5,558,50.355768,18096.210463,11774.100170,0,0,1,3
4,3,1.5,5.9,634,43.742292,18096.210463,11774.100170,1,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,53.538975,1508.576577,2753.428205,0,1,0,3
21248,2,-0.3,2.0,2000,48.487317,1508.576577,2753.428205,0,0,1,3
21249,1,4.7,0.6,137,55.215504,10826.115819,30619.671937,0,0,0,2
21250,2,2.3,1.1,950,53.850522,10826.115819,30619.671937,0,0,1,3
21251,1,33.9,1.7,2000,61.490694,1595.099346,2541.476440,0,0,1,3

In [ ]:
#df = pd.read_csv('./drive/MyDrive/final_data.csv',encoding='utf-8')

#df_test = pd.read_csv('./drive/MyDrive/final_test_data.csv',encoding='utf-8')
spark_df = sqlContext.createDataFrame(df)
#spark_df_test = sqlContext.createDataFrame(df_test)

In [ ]:
df.head()

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,등급
0,3,0.2,2.2,491,54.273750,18096.210463,11774.10017,1,0,0,3
1,2,9.3,1.9,703,49.554054,18096.210463,11774.10017,0,0,1,3
2,1,-4.2,1.8,2000,31.607682,18096.210463,11774.10017,0,1,0,3
3,1,-4.4,4.5,558,50.355768,18096.210463,11774.10017,0,0,1,3
4,3,1.5,5.9,634,43.742292,18096.210463,11774.10017,1,0,0,3

In [ ]:
from pyspark.ml.feature import VectorAssembler

# 1. Train/Test 데이터로 분할
train_df, test_df = spark_df.randomSplit(weights=[0.7, 0.3], seed=123)
#train_df = spark_df
#test_df = spark_df_test


# 2. Feature Vector로 만들기
ftr_columns = ['현장안전센터거리', '시간단위기온', '시간단위풍속', '시간단위가시거리', '실효습도',
       '전기사용량(KWh)', '가스사용량(KWh)', '화재발생시각_새벽', '화재발생시각_저녁', '화재발생시각_주간']
vec_assembler = VectorAssembler(inputCols=ftr_columns, outputCol='features') #features에는 하나의 칼럼.

train_ftr_vec = vec_assembler.transform(train_df)
test_ftr_vec = vec_assembler.transform(test_df)  # 테스트 데이터에 대해도 동일한 객체 사용
sparktrain_ftr_vec = vec_assembler.transform(test_df)

print('# 학습 원본 데이터:')
train_df.limit(5).show()

print('# Feature Vectorization 후 학습 데이터:')
train_ftr_vec.limit(5).show()

# 학습 원본 데이터:
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+
|현장안전센터거리|시간단위기온|시간단위풍속|시간단위가시거리|          실효습도|   전기사용량(KWh)|   가스사용량(KWh)|화재발생시각_새벽|화재발생시각_저녁|화재발생시각_주간|등급|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+
|               0|       -14.4|         2.0|            2000|         44.281887| 9949.277379066085|21762.540509124723|                0|                0|                0|   2|
|               0|       -12.7|         2.8|            2000| 53.32868400000001| 6579.535143847995| 7826.339856957087|                0|                0|                0|   2|
|               0|       -10.6|         1.7|            2000|53.760867000000005|  9339.12905468026|13023.231325301203|                1|                0|                0|   3|
|               0|       -10.3|         2.4|            1988|         42.964773|15989.908801133344| 17439.28899609465|                1|                0|                0|   3|
|               0|        -9.9|         2.8|            2000|53.760867000000005| 12319.52218133155|12643.047926089885|                1|                0|                0|   3|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+

# Feature Vectorization 후 학습 데이터:
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+
|현장안전센터거리|시간단위기온|시간단위풍속|시간단위가시거리|          실효습도|   전기사용량(KWh)|   가스사용량(KWh)|화재발생시각_새벽|화재발생시각_저녁|화재발생시각_주간|등급|            features|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+
|               0|       -14.4|         2.0|            2000|         44.281887| 9949.277379066085|21762.540509124723|                0|                0|                0|   2|[0.0,-14.4,2.0,20...|
|               0|       -12.7|         2.8|            2000| 53.32868400000001| 6579.535143847995| 7826.339856957087|                0|                0|                0|   2|[0.0,-12.7,2.8,20...|
|               0|       -10.6|         1.7|            2000|53.760867000000005|  9339.12905468026|13023.231325301203|                1|                0|                0|   3|[0.0,-10.6,1.7,20...|
|               0|       -10.3|         2.4|            1988|         42.964773|15989.908801133344| 17439.28899609465|                1|                0|                0|   3|[0.0,-10.3,2.4,19...|
|               0|        -9.9|         2.8|            2000|53.760867000000005| 12319.52218133155|12643.047926089885|                1|                0|                0|   3|[0.0,-9.9,2.8,200...|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+

#랜덤포레스트

In [ ]:
from pyspark.ml.classification import RandomForestClassifier

# 모델 정의
dt_clf = RandomForestClassifier(featuresCol='features', labelCol='등급', numTrees=2)

# 학습
dt_model = dt_clf.fit(train_ftr_vec)

# 학습, 테스트 데이터에 대해 예측
train_pred = dt_model.transform(train_ftr_vec)
test_pred = dt_model.transform(test_ftr_vec)

In [ ]:
train_pred.show()

+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|현장안전센터거리|시간단위기온|시간단위풍속|시간단위가시거리|          실효습도|   전기사용량(KWh)|   가스사용량(KWh)|화재발생시각_새벽|화재발생시각_저녁|화재발생시각_주간|등급|            features|       rawPrediction|         probability|prediction|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|               0|       -14.4|         2.0|            2000|         44.281887| 9949.277379066085|21762.540509124723|                0|                0|                0|   2|[0.0,-14.4,2.0,20...|[0.0,0.0139929521...|[0.0,0.0069964760...|       2.0|
|               0|       -12.7|         2.8|            2000| 53.32868400000001| 6579.535143847995| 7826.339856957087|                0|                0|                0|   2|[0.0,-12.7,2.8,20...|[0.0,0.0139929521...|[0.0,0.0069964760...|       2.0|
|               0|       -10.6|         1.7|            2000|53.760867000000005|  9339.12905468026|13023.231325301203|                1|                0|                0|   3|[0.0,-10.6,1.7,20...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|       -10.3|         2.4|            1988|         42.964773|15989.908801133344| 17439.28899609465|                1|                0|                0|   3|[0.0,-10.3,2.4,19...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -9.9|         2.8|            2000|53.760867000000005| 12319.52218133155|12643.047926089885|                1|                0|                0|   3|[0.0,-9.9,2.8,200...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -9.0|         2.5|            2000| 41.54413199999999|39493.830451000336| 32981.68928443436|                0|                0|                0|   2|[0.0,-9.0,2.5,200...|[0.0,0.0139929521...|[0.0,0.0069964760...|       2.0|
|               0|        -8.5|         4.7|            1894|         35.272713| 42438.10306030603|56661.654144675565|                0|                0|                1|   3|[0.0,-8.5,4.7,189...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -7.8|         0.7|            2000|         28.568805| 14193.46291304013| 16153.33122680309|                0|                0|                1|   3|[0.0,-7.8,0.7,200...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -7.5|         3.6|            1915|         29.921337| 35154.32723326382| 25684.75625446748|                0|                0|                1|   3|[0.0,-7.5,3.6,191...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -6.8|         5.3|            2000| 48.48731700000001| 6541.512393068655|11812.474932614556|                0|                1|                0|   3|[0.0,-6.8,5.3,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -6.2|         2.0|            1988|         38.085519| 9703.925853296589|16974.998783362484|                1|                0|                0|   3|[0.0,-6.2,2.0,198...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -6.1|         6.8|            2000| 52.48472399999999| 14255.64344193818| 20667.13190398509|                0|                0|                1|   3|[0.0,-6.1,6.8,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.9|         3.5|            2000|         33.417333| 40140.95923952182| 35038.03100202989|                0|                0|                1|   3|[0.0,-5.9,3.5,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.7|         1.4|            1610| 30.62502300000001| 6951.182051941373|10077.566817402152|                1|                0|                0|   3|[0.0,-5.7,1.4,161...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -5.7|         2.1|            1998|32.333535000000005| 12319.52218133155|12643.047926089885|                0|                1|                0|   3|[0.0,-5.7,2.1,199...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.4|         3.9|            2000|          41.83713|22353.135048951048| 79411.69047801734|                0|                1|                0|   3|[0.0,-5.4,3.9,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.2|         0.9|            1858|         42.042174| 9817.468647942522|17522.246207462074|                0|                0|                1|   3|[0.0,-5.2,0.9,185...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -5.2|         4.0|            1991|         37.622157| 40140.95923952182| 35038.03100202989|                0|                0|                1|   3|[0.0,-5.2,4.0,199...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.2|         5.0|            2000|         45.053583| 27981.56535650656|  22934.7519186684|                0|                0|                1|   3|[0.0,-5.2,5.0,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.0|         1.3|            1779|         33.905892|34614.514603044016|103006.63196480938|                1|                0|                0|   3|[0.0,-5.0,1.3,177...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
only showing top 20 rows

In [ ]:
test_pred.show()

+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|현장안전센터거리|시간단위기온|시간단위풍속|시간단위가시거리|          실효습도|   전기사용량(KWh)|   가스사용량(KWh)|화재발생시각_새벽|화재발생시각_저녁|화재발생시각_주간|등급|            features|       rawPrediction|         probability|prediction|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|               0|       -10.6|         1.7|            2000|         38.341068|14438.628358501666|29561.960814249363|                0|                0|                1|   3|[0.0,-10.6,1.7,20...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -9.6|         1.1|            1748|           29.6181|34614.514603044016|103006.63196480938|                0|                0|                1|   3|[0.0,-9.6,1.1,174...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -8.1|         1.7|            2000|         40.997517|15989.908801133344| 17439.28899609465|                1|                0|                0|   3|[0.0,-8.1,1.7,200...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -7.3|         0.3|            2000|         41.605767| 8464.798003370932|13634.082142138112|                0|                0|                1|   3|[0.0,-7.3,0.3,200...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -7.3|         2.3|            2000|         50.171109| 8464.798003370932|13634.082142138112|                1|                0|                0|   3|[0.0,-7.3,2.3,200...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -5.9|         4.6|            2000|         41.966559| 52495.57922696465|  68744.7428742515|                0|                1|                0|   3|[0.0,-5.9,4.6,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -5.2|         1.8|            1824|31.570053000000005|12122.605546792847| 16924.16365141303|                0|                0|                1|   3|[0.0,-5.2,1.8,182...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -4.5|         5.6|            2000|46.215765000000005|13753.070254110611| 12403.99421965318|                0|                1|                0|   3|[0.0,-4.5,5.6,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -4.2|         1.9|             418|46.737978000000005|14313.696300287356|28743.741781908862|                0|                0|                1|   3|[0.0,-4.2,1.9,418...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -3.4|         2.9|             582|         37.622157| 18957.61541061169|15773.710296434198|                1|                0|                0|   3|[0.0,-3.4,2.9,582...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -3.3|         1.3|            1407|         36.906273| 11991.30362487529|14899.883467023174|                0|                0|                1|   3|[0.0,-3.3,1.3,140...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -3.3|         1.5|             686|         53.406453| 12319.52218133155|12643.047926089885|                0|                0|                1|   3|[0.0,-3.3,1.5,686...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -2.9|         4.5|            2000|52.768755000000006|13753.070254110611| 12403.99421965318|                0|                0|                1|   3|[0.0,-2.9,4.5,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -2.7|         2.2|            1564|          41.82057| 9703.925853296589|16974.998783362484|                1|                0|                0|   3|[0.0,-2.7,2.2,156...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -2.3|         1.9|            1003|         42.992769| 7704.804038834952|  10590.9634601044|                0|                0|                1|   3|[0.0,-2.3,1.9,100...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -2.3|         3.7|            2000|          47.67576| 27981.56535650656|  22934.7519186684|                0|                1|                0|   3|[0.0,-2.3,3.7,200...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|        -0.7|         1.3|             608| 48.10143300000001| 7056.050821744627|20434.592536176693|                1|                0|                0|   3|[0.0,-0.7,1.3,608...|   [0.0,0.0,0.0,2.0]|   [0.0,0.0,0.0,1.0]|       3.0|
|               0|        -0.3|         0.9|            1825|         37.842879| 8464.798003370932|13634.082142138112|                0|                0|                0|   2|[0.0,-0.3,0.9,182...|[0.0,0.0148382217...|[0.0,0.0074191108...|       2.0|
|               0|        -0.2|         2.9|            1952| 44.10291900000001| 40140.95923952182| 35038.03100202989|                0|                0|                1|   3|[0.0,-0.2,2.9,195...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
|               0|         0.0|         4.0|            1793|         37.882662| 5394.894148020654| 6338.861881668283|                0|                0|                1|   3|[0.0,0.0,4.0,1793...|[0.0,0.0024227041...|[0.0,0.0012113520...|       3.0|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
only showing top 20 rows

In [ ]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(predictionCol='prediction', labelCol='등급', metricName='accuracy')

train_acc = evaluator.evaluate(train_pred)
test_acc = evaluator.evaluate(test_pred)

print('Train Accuracy:', train_acc)

Train Accuracy: 0.9970346407871681

In [ ]:
print('Test Accuracy:', test_acc)

Test Accuracy: 0.9954786404739632

#결정트리

In [ ]:
from pyspark.ml.classification import DecisionTreeClassifier

# 모델 정의
dt_clf = DecisionTreeClassifier(featuresCol='features', labelCol='등급', maxDepth=2)

# 학습
dt_model = dt_clf.fit(train_ftr_vec)

# 학습, 테스트 데이터에 대해 예측
train_pred = dt_model.transform(train_ftr_vec)
test_pred = dt_model.transform(test_ftr_vec)

In [ ]:
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(predictionCol='prediction', labelCol='등급', metricName='accuracy')

train_acc = evaluator.evaluate(train_pred)
test_acc = evaluator.evaluate(test_pred)

print('Train Accuracy:', train_acc)
print('Test Accuracy:', test_acc)

Train Accuracy: 0.9176438873163499
Test Accuracy: 0.914561895852822

In [ ]:
test_pred.show()

+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|현장안전센터거리|시간단위기온|시간단위풍속|시간단위가시거리|          실효습도|   전기사용량(KWh)|   가스사용량(KWh)|화재발생시각_새벽|화재발생시각_저녁|화재발생시각_주간|등급|            features|       rawPrediction|         probability|prediction|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
|               0|       -10.6|         1.7|            2000|         38.341068|14438.628358501666|29561.960814249363|                0|                0|                1|   3|[0.0,-10.6,1.7,20...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -9.6|         1.1|            1748|           29.6181|34614.514603044016|103006.63196480938|                0|                0|                1|   3|[0.0,-9.6,1.1,174...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -8.1|         1.7|            2000|         40.997517|15989.908801133344| 17439.28899609465|                1|                0|                0|   3|[0.0,-8.1,1.7,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -7.3|         0.3|            2000|         41.605767| 8464.798003370932|13634.082142138112|                0|                0|                1|   3|[0.0,-7.3,0.3,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -7.3|         2.3|            2000|         50.171109| 8464.798003370932|13634.082142138112|                1|                0|                0|   3|[0.0,-7.3,2.3,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -5.9|         4.6|            2000|         41.966559| 52495.57922696465|  68744.7428742515|                0|                1|                0|   3|[0.0,-5.9,4.6,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -5.2|         1.8|            1824|31.570053000000005|12122.605546792847| 16924.16365141303|                0|                0|                1|   3|[0.0,-5.2,1.8,182...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -4.5|         5.6|            2000|46.215765000000005|13753.070254110611| 12403.99421965318|                0|                1|                0|   3|[0.0,-4.5,5.6,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -4.2|         1.9|             418|46.737978000000005|14313.696300287356|28743.741781908862|                0|                0|                1|   3|[0.0,-4.2,1.9,418...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -3.4|         2.9|             582|         37.622157| 18957.61541061169|15773.710296434198|                1|                0|                0|   3|[0.0,-3.4,2.9,582...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -3.3|         1.3|            1407|         36.906273| 11991.30362487529|14899.883467023174|                0|                0|                1|   3|[0.0,-3.3,1.3,140...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -3.3|         1.5|             686|         53.406453| 12319.52218133155|12643.047926089885|                0|                0|                1|   3|[0.0,-3.3,1.5,686...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -2.9|         4.5|            2000|52.768755000000006|13753.070254110611| 12403.99421965318|                0|                0|                1|   3|[0.0,-2.9,4.5,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -2.7|         2.2|            1564|          41.82057| 9703.925853296589|16974.998783362484|                1|                0|                0|   3|[0.0,-2.7,2.2,156...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -2.3|         1.9|            1003|         42.992769| 7704.804038834952|  10590.9634601044|                0|                0|                1|   3|[0.0,-2.3,1.9,100...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -2.3|         3.7|            2000|          47.67576| 27981.56535650656|  22934.7519186684|                0|                1|                0|   3|[0.0,-2.3,3.7,200...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -0.7|         1.3|             608| 48.10143300000001| 7056.050821744627|20434.592536176693|                1|                0|                0|   3|[0.0,-0.7,1.3,608...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -0.3|         0.9|            1825|         37.842879| 8464.798003370932|13634.082142138112|                0|                0|                0|   2|[0.0,-0.3,0.9,182...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|        -0.2|         2.9|            1952| 44.10291900000001| 40140.95923952182| 35038.03100202989|                0|                0|                1|   3|[0.0,-0.2,2.9,195...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
|               0|         0.0|         4.0|            1793|         37.882662| 5394.894148020654| 6338.861881668283|                0|                0|                1|   3|[0.0,0.0,4.0,1793...|[0.0,21.0,1201.0,...|[0.0,0.0014152850...|       3.0|
+----------------+------------+------------+----------------+------------------+------------------+------------------+-----------------+-----------------+-----------------+----+--------------------+--------------------+--------------------+----------+
only showing top 20 rows