<a href="https://colab.research.google.com/github/ytg000629/Building_Safety_Indicator/blob/main/Modeling/%EB%AA%A8%EB%8D%B8%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('D:/학술제/찐최종전처리완.csv', encoding='utf-8')
df

,사망인명피해수,분기구분,화재발생일자,화재발생시,현장소방서거리,현장안전센터거리,현장소방지역대거리,발화요인대분류명,시설장소중분류명,방화관리대상여부,...,시간단위풍속,시간단위풍향,시간단위습도,시간단위가시거리,재산피해액,평균 상대습도(%),실효습도,주소,전기사용량(KWh),가스사용량(KWh)
0,0,1,20170101,0,4,3,0.0,전기적 요인,단독주택,Y,...,2.2,20.0,79.0,491,13391,75.9,54.273750,강남구 논현동,18096.210463,11774.100170
1,0,1,20170107,15,4,2,0.0,부주의,일상서비스,N,...,1.9,270.0,51.0,703,35,64.9,49.554054,강남구 논현동,18096.210463,11774.100170
2,0,1,20170115,20,5,1,0.0,부주의,음식점,N,...,1.8,250.0,43.0,2000,308,35.3,31.607682,강남구 논현동,18096.210463,11774.100170
3,0,1,20170120,10,4,1,0.0,부주의,음식점,Y,...,4.5,270.0,75.0,558,184,70.3,50.355768,강남구 논현동,18096.210463,11774.100170
4,0,1,20170127,3,5,3,0.0,부주의,단독주택,N,...,5.9,270.0,82.0,634,877,47.3,43.742292,강남구 논현동,18096.210463,11774.100170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21248,0,4,20201126,18,2,1,0.0,부주의,공동주택,N,...,2.2,290.0,56.0,1773,11,66.5,53.538975,용산구 신창동,1508.576577,2753.428205
21249,2,1,20210128,8,3,2,0.0,화학적 요인,공동주택,N,...,2.0,20.0,56.0,2000,4000,52.3,48.487317,용산구 신창동,1508.576577,2753.428205
21250,0,1,20200228,22,4,1,0.0,전기적 요인,단독주택,N,...,0.6,90.0,96.0,137,58,79.4,55.215504,성북구 삼선동3가,10826.115819,30619.671937
21251,0,4,20211229,12,4,2,0.0,부주의,공동주택,Y,...,1.1,50.0,76.0,950,18,72.9,53.850522,성북구 삼선동3가,10826.115819,30619.671937
21252,0,3,20210715,13,2,1,0.0,미상,연구/학원,Y,...,1.7,140.0,54.0,2000,38353,71.1,61.490694,종로구 권농동,1595.099346,2541.476440

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21253 entries, 0 to 21252
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   사망인명피해수     21253 non-null  int64
 1   분기구분        21253 non-null  int64
 2   화재발생일자      21253 non-null  int64
 3   화재발생시       21253 non-null  int64
 4   현장소방서거리     21253 non-null  int64
 5   현장안전센터거리    21253 non-null  int64
 6   현장소방지역대거리   21253 non-null  float64
 7   발화요인대분류명    21253 non-null  object
 8   시설장소중분류명    21253 non-null  object
 9   방화관리대상여부    21253 non-null  object
 10  시간단위기온      21253 non-null  float64
 11  시간단위풍속      21253 non-null  float64
 12  시간단위풍향      21253 non-null  float64
 13  시간단위습도      21253 non-null  float64
 14  시간단위가시거리    21253 non-null  int64
 15  재산피해액       21253 non-null  int64
 16  평균 상대습도(%)  21253 non-null  float64
 17  실효습도        21253 non-null  float64
 18  주소          21253 non-null  object
 19  전기사용량(KWh)  21253 non-null  float64
 20  가스사용량(KWh)  21253 non-null  float64
dtypes: float64(9), int64(8), object(4)
memory usage: 3.4+ MB

In [ ]:
df = df.drop(['분기구분', '화재발생일자', '현장소방서거리', '현장소방지역대거리', '발화요인대분류명', '시설장소중분류명', '시간단위습도', '평균 상대습도(%)', '주소', '방화관리대상여부', '시간단위풍향'], axis=1)

In [ ]:
df

,사망인명피해수,화재발생시,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh)
0,0,0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170
1,0,15,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170
2,0,20,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170
3,0,10,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170
4,0,3,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170
...,...,...,...,...,...,...,...,...,...,...
21248,0,18,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205
21249,2,8,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205
21250,0,22,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937
21251,0,12,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937
21252,0,13,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440

In [ ]:
df.to_csv('D:/학술제/data_final.csv', encoding='utf-8-sig', index=False)

In [ ]:
cls = []

for i in range(df.shape[0]):
    if df['화재발생시'][i] <=5 :
        cls.append('새벽')
    elif df['화재발생시'][i] <= 17:
        cls.append('주간')
    elif df['화재발생시'][i] <= 21:
        cls.append('저녁')
    else:
        cls.append('밤')

df['화재발생시각'] = cls
df = df.drop(['화재발생시'], axis=1)

In [ ]:
cls = []

for i in range(df.shape[0]):
    if df['사망인명피해수'][i] == 0:
        cls.append(0)
    else:
        cls.append(1)
        
df['타깃'] = cls
df = df.drop(['사망인명피해수'], axis=1)
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각,타깃
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,새벽,0
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,주간,0
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,저녁,0
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,주간,0
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,새벽,0
...,...,...,...,...,...,...,...,...,...,...
21248,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,저녁,0
21249,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,주간,1
21250,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,밤,0
21251,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,주간,0
21252,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,주간,0

In [ ]:
df['재산피해액'].sort_values()

1794            0
18150           0
12922           0
17888           0
1335            0
           ...
21050     1586332
7346      2397753
7932      2432471
19254     7512359
15468    71613336
Name: 재산피해액, Length: 21253, dtype: int64

In [ ]:
df = df.drop(15468, axis=0)

In [ ]:
X = df.drop(['타깃', '재산피해액'], axis=1)
y = df['타깃']

In [ ]:
X = pd.get_dummies(data=X, columns=['화재발생시각'], drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
X_train

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간
18699,1,10.2,0.7,354,60.312405,18630.938294,29702.066751,0,0,1
3821,3,18.1,0.2,755,59.253852,12122.605547,16924.163651,0,0,1
10126,2,18.7,1.0,695,62.371728,11772.405901,25200.481936,0,0,1
5577,1,-0.8,3.4,888,61.650228,22500.475735,14460.280016,0,1,0
18779,1,16.0,1.3,2000,51.650583,8661.961338,7138.864492,0,0,1
...,...,...,...,...,...,...,...,...,...,...
20240,1,20.9,2.1,1566,52.317960,5716.125069,5249.027885,0,0,1
19045,2,30.7,2.1,2000,55.792680,33491.513325,22587.539474,0,0,1
20626,1,32.5,2.5,2000,51.034074,5679.093423,7265.164384,0,1,0
13396,1,-11.6,2.1,1982,38.774829,7966.803563,8924.730213,1,0,0
13601,2,11.7,1.0,1532,42.517425,19489.935132,12144.852701,0,1,0

In [ ]:
X.columns[:7]

Index(['현장안전센터거리', '시간단위기온', '시간단위풍속', '시간단위가시거리', '실효습도', '전기사용량(KWh)',
       '가스사용량(KWh)'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np

for i in X.columns[:7]:
    scaler = StandardScaler()
    X_train[i] = scaler.fit_transform(np.array(X_train[i]).reshape(-1, 1))
    X_test[i] = scaler.transform(np.array(X_test[i]).reshape(-1, 1))
    X[i] = scaler.transform(np.array(X[i]).reshape(-1, 1))

In [ ]:
import statsmodels.api as sm


model = sm.Logit(y_train, X_train)

#3. 모델을 피팅한다.
results = model.fit(method='newton') # 뉴턴 메소드는 선형근사법이다. 로지스틱의 최적값을 피팅하는데 어려움이 있어 이와같은 방법을 사용 

#4. 예측하자
predicted_y = results.predict(X_test)
 

# 회귀 결과물들을 살펴보자
results.summary()

Optimization terminated successfully.
         Current function value: 0.225558
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     타깃   No. Observations:                17001
Model:                          Logit   Df Residuals:                    16991
Method:                           MLE   Df Model:                            9
Date:                Fri, 05 May 2023   Pseudo R-squ.:                 -0.2219
Time:                        18:34:17   Log-Likelihood:                -3834.7
converged:                       True   LL-Null:                       -3138.2
Covariance Type:            nonrobust   LLR p-value:                     1.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
현장안전센터거리       0.0007      0.032      0.023      0.981      -0.061       0.063
시간단위기온         0.0782      0.037      2.126      0.034       0.006       0.150
시간단위풍속         0.1605      0.032      5.029      0.000       0.098       0.223
시간단위가시거리      -0.0128      0.032     -0.395      0.692      -0.076       0.051
실효습도          -0.1231      0.037     -3.323      0.001      -0.196      -0.050
전기사용량(KWh)    -0.0315      0.041     -0.769      0.442      -0.112       0.049
가스사용량(KWh)     0.0680      0.040      1.720      0.085      -0.009       0.146
화재발생시각_새벽     -2.7237      0.080    -34.032      0.000      -2.881      -2.567
화재발생시각_저녁     -3.4326      0.096    -35.666      0.000      -3.621      -3.244
화재발생시각_주간     -3.0692      0.051    -59.828      0.000      -3.170      -2.969
==============================================================================
"""

In [ ]:
y_pred = predicted_y.apply(lambda x : 1 if x >= 0.5 else 0)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_pred, y_test)

0.9258997882851094

In [ ]:
prob = results.predict(X)

In [ ]:
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각,타깃
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,새벽,0
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,주간,0
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,저녁,0
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,주간,0
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,새벽,0
...,...,...,...,...,...,...,...,...,...,...
21248,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,저녁,0
21249,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,주간,1
21250,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,밤,0
21251,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,주간,0
21252,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,주간,0

In [ ]:
df['인명피해확률'] = prob

In [ ]:
df = df.drop('타깃', axis=1)

In [ ]:
df = pd.get_dummies(df, '화재발생시각', drop_first=True)

In [ ]:
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),인명피해확률,화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,0.052402,1,0,0
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,0.040359,0,0,1
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,0.030757,0,1,0
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,0.051458,0,0,1
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,0.094611,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
21248,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,0.027450,0,1,0
21249,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,0.038246,0,0,1
21250,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,0.432386,0,0,0
21251,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,0.035910,0,0,1
21252,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,0.039417,0,0,1

In [ ]:
df.to_csv('D:/학술제/확률추가최종.csv', encoding='utf-8-sig', index=False)

In [ ]:
import pandas as pd

df = pd.read_csv('D:/학술제/확률추가최종.csv', encoding='utf-8')
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),인명피해확률,화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,0.052402,1,0,0
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,0.040359,0,0,1
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,0.030757,0,1,0
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,0.051458,0,0,1
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,0.094611,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,0.027450,0,1,0
21248,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,0.038246,0,0,1
21249,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,0.432386,0,0,0
21250,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,0.035910,0,0,1
21251,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,0.039417,0,0,1

In [ ]:
X = df.drop(['재산피해액', '인명피해확률'], axis=1)
y = df['재산피해액']

In [ ]:
import numpy as np

y = np.log1p(y)

In [ ]:
X

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,실효습도,전기사용량(KWh),가스사용량(KWh),화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간
0,3,0.2,2.2,491,54.273750,18096.210463,11774.100170,1,0,0
1,2,9.3,1.9,703,49.554054,18096.210463,11774.100170,0,0,1
2,1,-4.2,1.8,2000,31.607682,18096.210463,11774.100170,0,1,0
3,1,-4.4,4.5,558,50.355768,18096.210463,11774.100170,0,0,1
4,3,1.5,5.9,634,43.742292,18096.210463,11774.100170,1,0,0
...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,53.538975,1508.576577,2753.428205,0,1,0
21248,2,-0.3,2.0,2000,48.487317,1508.576577,2753.428205,0,0,1
21249,1,4.7,0.6,137,55.215504,10826.115819,30619.671937,0,0,0
21250,2,2.3,1.1,950,53.850522,10826.115819,30619.671937,0,0,1
21251,1,33.9,1.7,2000,61.490694,1595.099346,2541.476440,0,0,1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [ ]:
import statsmodels.api as sm

lr = sm.OLS(y_train, X_train)
results = lr.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                  재산피해액   R-squared (uncentered):                   0.831
Model:                            OLS   Adj. R-squared (uncentered):              0.831
Method:                 Least Squares   F-statistic:                              8342.
Date:                Fri, 05 May 2023   Prob (F-statistic):                        0.00
Time:                        20:40:28   Log-Likelihood:                         -38466.
No. Observations:               17001   AIC:                                  7.695e+04
Df Residuals:                   16991   BIC:                                  7.703e+04
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
현장안전센터거리       0.1964      0.020      9.969      0.000       0.158       0.235
시간단위기온        -0.0288      0.002    -16.452      0.000      -0.032      -0.025
시간단위풍속         0.1095      0.016      6.979      0.000       0.079       0.140
시간단위가시거리       0.0005   2.85e-05     18.965      0.000       0.000       0.001
실효습도           0.0536      0.001     39.122      0.000       0.051       0.056
전기사용량(KWh)  1.615e-05   2.03e-06      7.950      0.000    1.22e-05    2.01e-05
가스사용량(KWh)  -1.84e-06    1.3e-06     -1.411      0.158    -4.4e-06    7.16e-07
화재발생시각_새벽      1.5449      0.069     22.545      0.000       1.411       1.679
화재발생시각_저녁      1.0991      0.068     16.068      0.000       0.965       1.233
화재발생시각_주간      1.4202      0.060     23.504      0.000       1.302       1.539
==============================================================================
Omnibus:                      431.122   Durbin-Watson:                   1.989
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              464.087
Skew:                           0.403   Prob(JB):                    1.68e-101
Kurtosis:                       3.063   Cond. No.                     1.84e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 1.84e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
y_pred = results.predict(X_test)
mean_absolute_error(y_pred, y_test)

1.8287109131092893

In [ ]:
df['회귀예측'] = results.predict(X)

In [ ]:
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),인명피해확률,화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,회귀예측
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,0.052402,1,0,0,5.814901
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,0.040359,0,0,1,5.060474
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,0.030757,0,1,0,4.657894
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,0.051458,0,0,1,5.507468
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,0.094611,1,0,0,5.695065
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,0.027450,0,1,0,5.178717
21248,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,0.038246,0,0,1,5.738874
21249,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,0.432386,0,0,0,3.279869
21250,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,0.035910,0,0,1,5.385773
21251,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,0.039417,0,0,1,5.224864

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
df['회귀예측'] = scaler.fit_transform(np.array(df['회귀예측']).reshape(-1, 1))*100

In [ ]:
scaler = MinMaxScaler()
df['인명피해확률'] = scaler.fit_transform(np.array(df['인명피해확률']).reshape(-1, 1))*100

In [ ]:
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),인명피해확률,화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,회귀예측
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,5.309739,1,0,0,70.074181
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,3.441645,0,0,1,56.333622
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,1.952044,0,1,0,49.001335
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,5.163348,0,0,1,64.474840
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,11.857381,1,0,0,67.891591
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,1.439104,0,1,0,58.487223
21248,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,3.113791,0,0,1,68.689487
21249,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,64.255049,0,0,0,23.903048
21250,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,2.751404,0,0,1,62.258379
21251,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,3.295456,0,0,1,59.327698

In [ ]:
df['지수'] = np.sqrt(df['회귀예측']*df['인명피해확률'])
df

,현장안전센터거리,시간단위기온,시간단위풍속,시간단위가시거리,재산피해액,실효습도,전기사용량(KWh),가스사용량(KWh),인명피해확률,화재발생시각_새벽,화재발생시각_저녁,화재발생시각_주간,회귀예측,지수
0,3,0.2,2.2,491,13391,54.273750,18096.210463,11774.100170,5.309739,1,0,0,70.074181,19.289261
1,2,9.3,1.9,703,35,49.554054,18096.210463,11774.100170,3.441645,0,0,1,56.333622,13.924092
2,1,-4.2,1.8,2000,308,31.607682,18096.210463,11774.100170,1.952044,0,1,0,49.001335,9.780224
3,1,-4.4,4.5,558,184,50.355768,18096.210463,11774.100170,5.163348,0,0,1,64.474840,18.245713
4,3,1.5,5.9,634,877,43.742292,18096.210463,11774.100170,11.857381,1,0,0,67.891591,28.372812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21247,1,7.1,2.2,1773,11,53.538975,1508.576577,2753.428205,1.439104,0,1,0,58.487223,9.174378
21248,2,-0.3,2.0,2000,4000,48.487317,1508.576577,2753.428205,3.113791,0,0,1,68.689487,14.624797
21249,1,4.7,0.6,137,58,55.215504,10826.115819,30619.671937,64.255049,0,0,0,23.903048,39.190452
21250,2,2.3,1.1,950,18,53.850522,10826.115819,30619.671937,2.751404,0,0,1,62.258379,13.088084
21251,1,33.9,1.7,2000,38353,61.490694,1595.099346,2541.476440,3.295456,0,0,1,59.327698,13.982554

In [ ]:
df['지수'].describe()

count    21252.000000
mean        18.292069
std         10.454247
min          0.000000
25%         13.054052
50%         15.915978
75%         18.853408
max         76.809331
Name: 지수, dtype: float64

In [ ]:
cls = []

for i in range(df.shape[0]):
    if df['지수'][i] >= 66:
        cls.append('1등급')
    elif df['지수'][i] >= 33:
        cls.append('2등급')
    else:
        cls.append('3등급')
        
df['등급'] = cls

In [ ]:
df['등급'].value_counts()

3등급    19482
2등급     1744
1등급       26
Name: 등급, dtype: int64