<a href="https://colab.research.google.com/github/ytg000629/Building_Safety_Indicator/blob/main/EDA_DataPreprocessing/%EC%8B%A4%ED%9A%A8%EC%8A%B5%EB%8F%84_%EC%B9%BC%EB%9F%BC_%EC%83%9D%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
상대습도17 = pd.read_csv("C:/Users/LG/Desktop/2017 상대습도.csv", encoding = 'cp949')
상대습도17=상대습도17[['평균 상대습도(%)','일시']]
상대습도18 = pd.read_csv("C:/Users/LG/Desktop/2018 상대습도.csv", encoding = 'cp949')
상대습도18=상대습도18[['평균 상대습도(%)','일시']]
상대습도19 = pd.read_csv("C:/Users/LG/Desktop/2019 상대습도.csv", encoding = 'cp949')
상대습도19=상대습도19[['평균 상대습도(%)','일시']]
상대습도20 = pd.read_csv("C:/Users/LG/Desktop/2020 상대습도.csv", encoding = 'cp949')
상대습도20=상대습도20[['평균 상대습도(%)','일시']]
상대습도21 = pd.read_csv("C:/Users/LG/Desktop/2021 상대습도.csv", encoding = 'cp949')
상대습도21=상대습도21[['평균 상대습도(%)','일시']]

In [ ]:
상대습도 = pd.concat([상대습도17, 상대습도18, 상대습도19, 상대습도20, 상대습도21])

In [ ]:
상대습도

     평균 상대습도(%)          일시
0          75.9  2017-01-01
1          77.8  2017-01-02
2          61.8  2017-01-03
3          55.0  2017-01-04
4          52.3  2017-01-05
..          ...         ...
360        60.9  2021-12-27
361        73.8  2021-12-28
362        72.9  2021-12-29
363        48.5  2021-12-30
364        35.9  2021-12-31

[1826 rows x 2 columns]

In [ ]:
상대습도.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1826 entries, 0 to 364
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   평균 상대습도(%)  1826 non-null   float64
 1   일시          1826 non-null   object
dtypes: float64(1), object(1)
memory usage: 42.8+ KB

In [ ]:
상대습도20
#윤년

     평균 상대습도(%)          일시
0          64.4  2020-01-01
1          65.4  2020-01-02
2          56.9  2020-01-03
3          50.8  2020-01-04
4          45.6  2020-01-05
..          ...         ...
361        62.9  2020-12-27
362        72.1  2020-12-28
363        70.8  2020-12-29
364        55.5  2020-12-30
365        53.9  2020-12-31

[366 rows x 2 columns]

In [ ]:
import re
상대습도['일시']=상대습도['일시'].str.replace(pat = r'-', repl=r'', regex=True)

In [ ]:
상대습도

     평균 상대습도(%)        일시
0          75.9  20170101
1          77.8  20170102
2          61.8  20170103
3          55.0  20170104
4          52.3  20170105
..          ...       ...
360        60.9  20211227
361        73.8  20211228
362        72.9  20211229
363        48.5  20211230
364        35.9  20211231

[1826 rows x 2 columns]

In [ ]:
r=0.7

In [ ]:
list = []

In [ ]:
for i in range(1822):
    a=(1-r)*(상대습도.iloc[i+4,0] + 상대습도.iloc[i+3,0]*r + 상대습도.iloc[i+2,0]*r*r + 상대습도.iloc[i+1,0]*r*r*r + 상대습도.iloc[i,0]*r*r*r*r)
    list.append(a)

In [ ]:
list.insert(0, 57.47292)
list.insert(0, 57.37625)
list.insert(0, 56.26225)
list.insert(0, 54.27375)

In [ ]:
list

[54.27375,
 56.26225,
 57.37625,
 57.47292,
 49.797297,
 48.581154000000005,
 49.554054,
 49.991820000000004,
 50.461119000000004,
 46.215765000000005,
 40.321407,
 37.882662,
 37.642014,
 33.273813,
 31.607681999999997,
 31.570053000000005,
 33.905892,
 42.01416900000001,
 44.350899,
 50.355768000000005,
 56.783208,
 52.788627000000005,
 47.998031999999995,
 45.685299,
 43.615113,
 45.912699,
 43.742292000000006,
 39.579228,
 46.534578,
 48.442902,
 44.10291900000001,
 41.837129999999995,
 43.239993000000005,
 46.303062000000004,
 50.136294,
 55.426545000000004,
 51.854847,
 47.251122,
 44.808251999999996,
 41.966559,
 38.86989,
 38.257452,
 39.881103,
 43.27068,
 41.719689,
 42.600132,
 46.700979000000004,
 47.174088,
 44.83677,
 49.466373,
 48.139527,
 41.605767,
 47.495082000000004,
 47.675760000000004,
 45.334404000000006,
 48.10143300000001,
 47.640384000000005,
 40.998461999999996,
 38.305178999999995,
 43.727028,
 45.252144,
 45.334272000000006,
 47.848245000000006,
 52.88130000000001,
 46.129545,
 40.540632,
 40.81554,
 39.735618,
 35.424789,
 33.934965000000005,
 39.383688,
 39.957279,
 36.835181999999996,
 34.368882,
 34.712472000000005,
 34.284144000000005,
 31.717935,
 31.111767000000007,
 32.138544,
 34.819383,
 32.040423000000004,
 30.908939999999998,
 32.241102000000005,
 32.861763,
 36.507984,
 44.12178000000001,
 47.110932,
 47.36022300000001,
 46.07985300000001,
 50.75854200000001,
 50.282604000000006,
 48.112647,
 44.590740000000004,
 39.282468,
 43.738005,
 54.566133,
 55.948938000000005,
 59.215059000000004,
 57.55068000000001,
 44.69769000000001,
 37.790493000000005,
 29.559675000000006,
 33.135408000000005,
 37.559694,
 42.810924,
 43.98215400000001,
 49.63833,
 54.974097000000015,
 48.49249200000001,
 44.569736999999996,
 45.481545000000004,
 43.004084999999996,
 38.245653000000004,
 36.418812,
 40.244054999999996,
 36.122052000000004,
 35.38506,
 39.942702000000004,
 39.263304000000005,
 41.9904,
 42.818124,
 40.465089,
 35.666439000000004,
 35.812857,
 38.169624000000006,
 33.75735,
 34.292463000000005,
 35.365368000000004,
 41.337402000000004,
 48.1437,
 51.67711800000001,
 55.506048,
 59.995878,
 56.330760000000005,
 54.170799,
 52.77706799999999,
 48.783804,
 42.795908999999995,
 39.797592,
 37.96246500000001,
 37.953255000000006,
 40.05059700000001,
 46.32277800000001,
 48.39801000000001,
 45.340083,
 41.762808,
 40.3614,
 40.004352000000004,
 43.497618,
 41.199135,
 41.476923,
 42.249438,
 38.243304,
 36.854295,
 34.674693,
 31.786614000000004,
 37.638822,
 51.881430000000016,
 54.28847700000001,
 57.08139900000001,
 52.31796000000001,
 43.73731200000001,
 39.657639,
 43.267013999999996,
 45.66752400000001,
 48.327564,
 48.86506500000001,
 47.60138999999999,
 45.74444999999999,
 44.114592,
 40.753944000000004,
 41.494269,
 43.59897,
 43.79738700000001,
 46.211742,
 52.779948000000005,
 57.363819000000014,
 57.51555000000001,
 56.638572,
 56.04157200000001,
 55.197357000000004,
 56.840774999999994,
 63.535125,
 67.55285400000001,
 66.36971700000001,
 63.206058,
 62.223255,
 63.233178,
 64.836345,
 68.02907700000002,
 73.197189,
 72.012594,
 69.104799,
 65.47329,
 61.914255000000004,
 65.17435200000001,
 66.53777699999999,
 65.93949,
 66.757752,
 64.70163000000001,
 60.633672000000004,
 60.16845900000001,
 60.960378,
 65.458332,
 66.910773,
 62.734713000000006,
 56.90852400000001,
 54.764055,
 61.45215900000001,
 60.556863,
 58.477818,
 62.821065,
 62.72343300000001,
 60.83262900000001,
 57.117402,
 54.76506900000001,
 53.0859,
 55.04939700000001,
 55.339308,
 55.81200299999999,
 55.9581,
 62.964147,
 62.199633000000006,
 58.196073,
 55.984002000000004,
 56.09084700000001,
 62.870745000000014,
 64.503999,
 65.242413,
 65.218545,
 64.989564,
 69.443205,
 69.00135300000001,
 65.593488,
 67.333614,
 68.901618,
 61.980885,
 55.62730799999999,
 53.97939300000001,
 55.475168999999994,
 49.951707000000006,
 48.585135,
 49.98165,
 48.661053,
 48.076962,
 50.262234,
 48.510072,
 49.53078,
 54.49797000000001,
 57.163740000000004,
 57.03767400000001,
 58.243722000000005,
 59.914335,
 62.073249000000004,
 57.335415000000005,
 51.52137299999999,
 47.170449000000005,
 43.793034000000006,
 41.901528,
 41.76639900000001,
 45.590724,
 53.182961999999996,
 49.457697,
 49.243959000000004,
 50.124174000000004,
 52.860482999999995,
 54.464037000000005,
 53.059239000000005,
 51.352343999999995,
 52.801044,
 48.171345,
 41.90484,
 45.87897,
 51.681282,
 51.51894299999999,
 48.52758899999999,
 46.537766999999995,
 46.22411399999999,
 48.505389,
 51.09254400000001,
 53.32381500000001,
 54.68125200000001,
 58.503132000000015,
 60.73423800000001,
 60.405507000000014,
 54.21069,
 47.459697,
 42.094413,
 39.85863,
 38.451150000000005,
 41.984334,
 44.721015,
 46.74181800000001,
 46.159233,
 45.056633999999995,
 42.67488899999999,
 43.222878,
 45.001343999999996,
 45.788712,
 45.83088,
 45.281829,
 42.63942000000001,
 35.092755,
 38.006142,
 45.581397,
 52.930128,
 54.55189200000001,
 51.174789000000004,
 48.83449200000001,
 49.883664,
 49.365390000000005,
 47.217987,
 42.517424999999996,
 44.005095,
 40.421412000000004,
 42.329139,
 46.262958000000005,
 43.137399,
 38.847477,
 34.12017300000001,
 32.825082,
 31.280445000000004,
 31.093419000000004,
 36.424269,
 40.649232,
 42.907875000000004,
 42.884304,
 46.863099,
 53.29588800000001,
 55.983714,
 52.325528999999996,
 53.372115,
 48.69916799999999,
 38.216747999999995,
 37.961580000000005,
 41.870793000000006,
 51.007569,
 47.699963999999994,
 44.068692000000006,
 50.137287,
 51.425883,
 44.198133,
 42.34344299999999,
 47.988527999999995,
 42.081405000000004,
 38.774829000000004,
 37.659993,
 36.907587,
 38.191725000000005,
 37.622157,
 35.65287,
 46.839327000000004,
 45.44446800000001,
 49.558983000000005,
 53.938143000000004,
 55.81566,
 57.777282,
 62.5533,
 53.288682,
 46.24201800000001,
 38.431374000000005,
 37.18005,
 41.991513000000005,
 51.07091400000001,
 49.96204200000001,
 45.12021000000001,
 41.81436000000001,
 38.581845,
 35.898822,
 36.906273,
 37.60293,
 36.834369,
 39.22125,
 43.10677199999999,
 43.33436400000001,
 42.964772999999994,
 38.572616999999994,
 44.57398200000001,
 47.43678,
 49.75385399999999,
 50.046732,
 52.47780900000001,
 51.22113300000001,
 45.522807,
 45.924063000000004,
 40.146963,
 41.820888,
 38.869530000000005,
 34.520568000000004,
 31.040148000000002,
 30.352694999999997,
 29.618100000000002,
 29.414988,
 29.497188,
 37.604307000000006,
 40.91332200000001,
 39.98358,
 41.50335000000001,
 41.38761,
 38.115225,
 35.272713,
 33.417333,
 32.75562,
 33.549147,
 34.592183999999996,
 36.528615,
 36.47966400000001,
 35.769009000000004,
 39.205077,
 40.530072000000004,
 34.38109500000001,
 33.953874,
 29.390535,
 25.89543,
 30.135330000000003,
 31.982943000000002,
 29.816178,
 37.280547000000006,
 49.070057999999996,
 46.718579999999996,
 42.81574500000001,
 41.31276,
 40.584093,
 46.309722,
 48.496008,
 42.10011299999999,
 38.726934,
 51.37830900000001,
 52.51895700000001,
 47.682210000000005,
 47.863232999999994,
 54.38322300000001,
 52.565745000000014,
 53.132604,
 50.223119999999994,
 46.17345,
 46.63941900000001,
 47.095943999999996,
 57.279458999999996,
 51.579024,
 48.196035,
 47.456754,
 49.604972999999994,
 42.049707,
 46.300050000000006,
 48.43982700000001,
 47.679345,
 48.693387,
 51.753572999999996,
 52.34551499999999,
 51.870969,
 53.44139700000001,
 54.177918000000005,
 51.296925,
 48.525693000000004,
 51.52726199999999,
 51.921129,
 54.87187800000001,
 55.706907,
 63.50756400000001,
 62.46632999999999,
 54.149487,
 52.10895,
 50.468058000000006,
 46.059498000000005,
 43.451505000000004,
 37.27189800000001,
 29.955236999999997,
 41.68929,
 46.26103200000001,
 42.46192500000001,
 39.555507000000006,
 37.154213999999996,
 33.674775000000004,
 34.069767000000006,
 31.336197000000002,
 37.244382,
 52.45616400000001,
 53.75298000000001,
 46.64772,
 46.609932,
 45.602787,
 41.88741900000001,
 39.059544,
 43.915767,
 49.964187,
 59.42766000000002,
 57.848733,
 51.970968,
 47.313744,
 55.368972,
 52.29022199999999,
 48.726884999999996,
 46.934664000000005,
 50.71456200000001,
 49.083819,
 58.108287,
 62.859372,
 62.880342,
 57.537864,
 65.40132899999999,
 70.378335,
 71.14510200000001,
 60.451512,
 49.10231399999999,
 42.81213,
 47.727654,
 46.162815,
 44.13897300000001,
 43.49876700000001,
 43.265655,
 40.699173,
 40.550382,
 46.78531200000001,
 51.299763,
 51.05374200000001,
 48.467664000000006,
 44.766399,
 39.662304,
 39.274227,
 40.272162,
 44.51929500000001,
 49.709772,
 53.210253,
 52.901085,
 52.353657,
 53.666078999999996,
 53.72208,
 53.37682800000001,
 56.77826700000001,
 54.964569,
 52.00186500000001,
 53.168730000000004,
 50.461166999999996,
 49.936284,
 52.319802,
 51.810117000000005,
 46.423917,
 44.908629000000005,
 47.185233000000004,
 46.72599300000001,
 56.16789299999999,
 61.61353800000001,
 66.108174,
 66.659283,
 68.922459,
 72.17354700000001,
 75.012003,
 70.537575,
 66.298254,
 64.02349799999999,
 57.386621999999996,
 50.780471999999996,
 47.245008,
 54.252204000000006,
 60.645894000000006,
 64.40779200000001,
 67.21381500000001,
 66.89298900000001,
 63.555444,
 60.941846999999996,
 57.76939199999999,
 56.23388399999999,
 55.032228,
 54.243258,
 53.240979,
 50.106615,
 46.60163400000001,
 45.493863000000005,
 46.463718,
 49.258248,
 52.418208,
 54.981864000000016,
 58.90465499999999,
 53.95320900000001,
 49.694334000000005,
 46.467069,
 45.682773000000005,
 44.41048200000001,
 45.035277,
 47.138265000000004,
 51.990525000000005,
 55.075002,
 54.829598999999995,
 55.032438,
 58.35719400000001,
 55.499808,
 51.979721999999995,
 51.579114,
 53.418099,
 51.035547,
 50.504244000000014,
 47.83947900000001,
 42.336828000000004,
 39.556899,
 39.930285,
 41.631150000000005,
 47.99033400000001,
 47.81647800000001,
 48.952757999999996,
 57.605627999999996,
 57.920532,
 57.94431300000001,
 65.13324300000001,
 70.333389,
 70.68204000000001,
 70.31880000000001,
 65.91369,
 59.371272000000005,
 53.64099,
 58.802487000000006,
 57.902682000000006,
 56.183502000000004,
 57.30344400000001,
 53.67891899999999,
 47.914331999999995,
 44.740815000000005,
 42.966837,
 40.982358000000005,
 41.53466400000001,
 45.663720000000005,
 49.563975000000006,
 54.998943000000004,
 61.15401,
 59.47591500000001,
 56.371407000000005,
 53.81682000000001,
 58.55977800000001,
 62.51664900000001,
 59.20958400000001,
 54.301533000000006,
 49.521192,
 44.910143999999995,
 41.480979000000005,
 40.175457,
 42.885549,
 44.234550000000006,
 44.293977,
 45.12061800000001,
 47.604392999999995,
 47.793614999999996,
 47.607165,
 55.90791300000001,
 61.55734200000001,
 56.04429000000001,
 50.406585,
 48.185823000000006,
 47.78967,
 44.517405000000004,
 44.66465999999999,
 45.095475,
 46.91973,
 50.73813000000001,
 49.715219999999995,
 48.067919999999994,
 48.77481,
 47.407107,
 45.83054700000001,
 44.112849000000004,
 43.191555,
 49.764039000000004,
 51.896967,
 50.260185,
 54.916290000000004,
 50.80035300000001,
 54.90363,
 52.294755,
 49.197963,
 47.32237800000001,
 46.644783,
 45.233889000000005,
 45.574599,
 45.815622,
 48.927612,
 52.706847,
 57.97668,
 65.9001,
 64.05691500000002,
 62.26726500000001,
 60.312405,
 53.900214000000005,
 48.48066,
 47.107413,
 46.111098000000005,
 48.39930900000001,
 46.482498,
 44.576024999999994,
 43.524852,
 39.64407299999999,
 41.598444,
 37.057524,
 32.359722000000005,
 41.44058700000001,
 50.336613,
 53.38659,
 55.10587799999999,
 45.211653,
 40.483224,
 38.245503,
 35.92734,
 36.901773,
 50.684832,
 55.861953000000014,
 48.62895900000001,
 47.057463000000006,
 41.54413199999999,
 35.804097000000006,
 29.386335,
 28.568804999999998,
 30.891903,
 31.453713,
 37.36698,
 38.085519,
 39.020844,
 44.195730000000005,
 47.000592000000005,
 46.896249000000005,
 46.61372400000001,
 43.919903999999995,
 39.557072999999995,
 39.329649,
 37.592052,
 34.391955,
 37.80021300000001,
 36.678267,
 31.6992,
 29.921337,
 27.834822000000003,
 27.561894,
 29.116149000000007,
 33.804390000000005,
 34.83918,
 34.565217,
 39.035537999999995,
 37.418205,
 34.196903999999996,
 35.699814,
 32.333535000000005,
 28.475109,
 32.54061,
 38.653692,
 38.99805,
 42.02558400000001,
 48.545784,
 49.161504,
 45.21829800000001,
 42.992769,
 40.557078000000004,
 42.871074,
 38.594997,
 42.042173999999996,
 45.72024,
 44.455644,
 38.573775000000005,
 33.340434,
 29.69397,
 33.409677,
 33.04118700000001,
 32.019138000000005,
 37.401777,
 33.323235,
 34.959162000000006,
 40.434405,
 54.38413800000001,
 47.43591000000001,
 42.87292800000001,
 44.081010000000006,
 41.481447,
 33.802902,
 30.625023000000006,
 28.956897,
 27.971715000000007,
 27.936045,
 25.946970000000004,
 23.940249,
 37.019997000000004,
 41.854305,
 41.72806800000001,
 40.918449,
 51.657684,
 52.82973,
 51.825972,
 50.718225,
 45.609444,
 41.352593999999996,
 42.268272,
 36.432783,
 32.06433,
 32.22777,
 32.980494,
 31.552854,
 31.353189000000004,
 34.199055,
 41.837709000000004,
 43.653588000000006,
 43.991682000000004,
 40.778853000000005,
 35.760788999999995,
 29.609640000000002,
 36.253593,
 39.331002,
 37.095113999999995,
 37.953192,
 47.076119999999996,
 50.84760300000001,
 49.435125000000006,
 45.803379,
 45.378294,
 51.794157,
 55.951482,
 48.642714,
 45.911460000000005,
 43.13613,
 43.042032,
 41.556837,
 46.947567000000014,
 45.468552,
 39.468873,
 46.399593,
 43.70320200000001,
 39.184287,
 35.982993,
 34.34916,
 33.3141,
 33.300504,
 33.273597,
 34.360983000000004,
 29.912490000000002,
 33.500640000000004,
 44.90318700000002,
 46.820433,
 45.151158,
 40.515032999999995,
 39.534852,
 32.99139,
 28.059554999999996,
 28.44627,
 40.518075,
 43.31849700000001,
 48.834939000000006,
 56.198385,
 52.628082000000006,
 48.688335,
 52.30262700000001,
 56.008674,
 59.913318000000004,
 55.168020000000006,
 50.63572200000001,
 47.76536700000001,
 45.448803000000005,
 42.34459799999999,
 35.539074,
 33.666807000000006,
 33.01949400000001,
 31.191417,
 27.498404999999998,
 27.831885,
 32.081532,
 33.410064,
 35.981973,
 35.520972,
 33.980619000000004,
 34.371099,
 35.22654,
 36.66837,
 36.84144,
 37.44385200000001,
 38.062425,
 52.29996300000001,
 53.264724,
 50.676866999999994,
 47.009904000000006,
 44.04722999999999,
 40.063908,
 38.51796,
 36.04068000000001,
 47.17911000000001,
 44.52643200000001,
 43.348968000000006,
 42.445080000000004,
 42.625137,
 43.908537,
 41.051652,
 39.16578,
 41.91583800000001,
 45.980205000000005,
 51.905673,
 57.40124700000001,
 55.267812000000006,
 55.673724,
 56.84474700000001,
 51.29436900000001,
 49.138515000000005,
 47.067753,
 46.054599,
 47.143623,
 47.044023,
 47.781777,
 54.410394,
 58.66420500000001,
 59.144052,
 60.477513,
 52.044378,
 44.587974,
 41.358828,
 40.12145700000001,
 40.189329,
 47.149722000000004,
 51.157797,
 55.04571299999999,
 58.106328000000005,
 57.34228500000001,
 55.634919000000004,
 54.931110000000004,
 52.701465000000006,
 45.815082,
 41.093445,
 38.553678000000005,
 37.710378000000006,
 37.312173,
 43.225797,
 51.26583900000001,
 53.352858,
 55.187382,
 55.671633,
 59.738157,
 61.63933500000001,
 62.014959000000005,
 59.517138,
 56.79480000000001,
 55.792680000000004,
 61.20161700000001,
 61.49502000000001,
 61.009149,
 64.305597,
 68.670753,
 72.26785800000002,
 69.806094,
 71.784459,
 68.449473,
 65.961699,
 68.698068,
 70.146399,
 67.030305,
 63.86484900000001,
 63.678693,
 59.63173200000001,
 52.80583800000001,
 56.63268000000001,
 57.58382700000001,
 57.18172500000001,
 54.094632,
 51.354603000000004,
 59.550342,
 61.15518,
 58.499577,
 62.630328000000006,
 63.488664000000014,
 60.66341700000001,
 58.537017000000006,
 55.93401000000001,
 51.90928500000001,
 52.770135,
 53.384834999999995,
 51.536387999999995,
 51.28995900000001,
 53.04426899999999,
 52.87765499999999,
 54.991362,
 55.409367,
 58.845918000000005,
 57.72410399999999,
 56.69001300000001,
 55.29807600000001,
 52.35078300000001,
 53.038089,
 60.483750000000015,
 66.48126,
 67.24993800000001,
 66.091128,
 65.92533,
 63.950262,
 68.176704,
 65.12009700000002,
 63.598377,
 58.761489000000005,
 61.386762000000004,
 59.38141200000001,
 53.866929,
 46.541411999999994,
 43.333560000000006,
 40.249812,
 40.465230000000005,
 43.743348,
 47.54283,
 46.290615,
 48.448854000000004,
 50.571968999999996,
 50.149992000000005,
 49.158303,
 ...]

In [ ]:
상대습도['실효습도'] = list

In [ ]:
상대습도

     평균 상대습도(%)        일시       실효습도
0          75.9  20170101  54.273750
1          77.8  20170102  56.262250
2          61.8  20170103  57.376250
3          55.0  20170104  57.472920
4          52.3  20170105  49.797297
..          ...       ...        ...
360        60.9  20211227  44.210775
361        73.8  20211228  50.390019
362        72.9  20211229  53.850522
363        48.5  20211230  50.107515
364        35.9  20211231  43.651947

[1826 rows x 3 columns]

In [ ]:
상대습도.to_csv('실효습도.csv', encoding="utf-8-sig",index=False)